name: tairon_app
description: "Aplicación de Hidallgo's - Contratista General"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/logo_tairon.png
    - assets/logo_tairon_new.png
    - assets/logo_tairon_transparent.png
    - assets/ducha moderna.png
    - assets/gabinete de baño.png
    - assets/chaguer.png
    - assets/lavamanos.jpg
    - assets/grifo de cocina.jpg
    - assets/inodoro moderno.png
